import {TokenKind, TokenObject, StringToken} from '../compiler_tokenizer/tokenObject';
import {diagnostic} from '../core/diagnostic';
import {HighlightForModifier, HighlightForToken} from '../core/highlight';
import {TokenRange} from '../compiler_tokenizer/tokenRange';
import {TextLocation, TextPosition} from '../compiler_tokenizer/textLocation';
import * as assert from 'node:assert';

/**
 * Output of `preprocessAfterTokenize`.
 */
export interface PreprocessedOutput {
    readonly preprocessedTokens: TokenObject[];
    readonly includePathTokens: StringToken[];
    readonly definedSymbols: Set<string>; // '#define SYMBOL'
}

interface IntermediateOutput {
    readonly preprocessedTokens: TokenObject[]; // Tokens with comments removed and directives processed
    readonly includePathTokens: StringToken[];
    readonly definedSymbols: Set<string>; // '#define SYMBOL'
}

/**
 * Preprocess the token list before parsing.
 * For example, this removes comments, concatenates adjacent strings, and handles directives.
 * @param rawTokens Tokens generated by the tokenizer.
 * @param externalDefinedSymbols
 */
export function preprocessAfterTokenize(
    rawTokens: TokenObject[],
    externalDefinedSymbols: string[]
): PreprocessedOutput {
    // Handle preprocessor directives.
    const intermediateOutput = preprocessDirectives(rawTokens, externalDefinedSymbols);

    // Concatenate adjacent string literals.
    const preprocessedTokens = intermediateOutput.preprocessedTokens;
    for (let i = preprocessedTokens.length - 1; i >= 1; i--) {
        const canCombine = preprocessedTokens[i - 1].isStringToken() && preprocessedTokens[i].isStringToken(); // "string" --> "string"
        if (!canCombine) {
            continue;
        }

        // Create a new token from the combined string literals.
        // e.g., "string2" + "string2" --> "string1string2"
        preprocessedTokens[i - 1] = createCombinedStringToken(
            preprocessedTokens[i - 1] as StringToken,
            preprocessedTokens[i] as StringToken
        );
        preprocessedTokens.splice(i, 1);
    }

    // Assign index information.
    for (let i = 0; i < preprocessedTokens.length; i++) {
        preprocessedTokens[i].bindPreprocessedToken(
            i,
            i != preprocessedTokens.length - 1 ? preprocessedTokens[i + 1] : undefined
        );
    }

    return {
        preprocessedTokens: preprocessedTokens,
        includePathTokens: intermediateOutput.includePathTokens,
        definedSymbols: intermediateOutput.definedSymbols
    };
}

type IfDirectiveBlock = {
    tag: '#if';
    start: TextLocation;
    isActiveBlock: boolean;
    hasActiveBranch: boolean;
    hasElse: boolean;
};

interface DirectivePreprocessorContext {
    ifDirectiveBlockStack: IfDirectiveBlock[];
    isActiveBlock: boolean;
    intermediateOutput: IntermediateOutput;
}

function getCurrentIfDirectiveBlock(context: DirectivePreprocessorContext): IfDirectiveBlock | undefined {
    if (context.ifDirectiveBlockStack.length === 0) {
        return undefined;
    }

    return context.ifDirectiveBlockStack[context.ifDirectiveBlockStack.length - 1];
}

function updateInactiveBlockStatus(context: DirectivePreprocessorContext) {
    for (const block of context.ifDirectiveBlockStack) {
        if (!block.isActiveBlock) {
            context.isActiveBlock = false;
            return;
        }
    }

    context.isActiveBlock = true;
}

function getDirectiveBlockStart(directiveTokens: TokenObject[]): TextLocation {
    const directiveTail = directiveTokens[directiveTokens.length - 1];
    return (directiveTail.nextRaw ?? directiveTail).location;
}

function reportInactiveDirectiveBlockIfNeeded(
    context: DirectivePreprocessorContext,
    currentIfDirectiveBlock: IfDirectiveBlock,
    end: TextPosition
) {
    if (!context.isActiveBlock) {
        diagnostic.unnecessary(currentIfDirectiveBlock.start.withEnd(end), 'Inactive #if branch');
    }
}

function evaluateIfDirectiveCondition(
    context: DirectivePreprocessorContext,
    conditionToken: TokenObject
): boolean | undefined {
    switch (conditionToken.kind) {
        case TokenKind.Identifier:
            return context.intermediateOutput.definedSymbols.has(conditionToken.text);
        case TokenKind.Number: {
            assert(conditionToken.isNumberToken());
            const value = conditionToken.getNumberValue();
            return value === undefined ? undefined : value !== 0;
        }
        default:
            return undefined;
    }
}

function getIfDirectiveCondition(
    context: DirectivePreprocessorContext,
    directiveTokens: TokenObject[]
): boolean | undefined {
    const conditionToken = directiveTokens[2];
    if (conditionToken === undefined) {
        diagnostic.error(directiveTokens[1].location, 'Expected a identifier or number token.');
        return undefined;
    }

    const condition = evaluateIfDirectiveCondition(context, conditionToken);
    if (condition === undefined) {
        diagnostic.error(conditionToken.location, 'Expected a identifier or number token.');
    }

    return condition;
}

function preprocessDirectives(rawTokens: TokenObject[], externalDefinedSymbols: string[]): IntermediateOutput {
    const context: DirectivePreprocessorContext = {
        ifDirectiveBlockStack: [],
        isActiveBlock: true,
        intermediateOutput: {
            preprocessedTokens: [],
            includePathTokens: [],
            definedSymbols: new Set(externalDefinedSymbols)
        }
    };

    // Handle preprocessor directives that start with `#`.
    let previousLine = -1;
    for (let i = 0; i < rawTokens.length; i++) {
        if (rawTokens[i].location.start.line !== previousLine) {
            previousLine = rawTokens[i].location.end.line;

            if (rawTokens[i].text === '#') {
                // Handle the directive.
                const directiveTokens = sliceTokenListBySameLine(rawTokens, i);

                handleDirectiveTokens(context, directiveTokens);

                i += directiveTokens.length - 1;
                continue;
            }
        }

        if (!rawTokens[i].isCommentToken() && context.isActiveBlock) {
            context.intermediateOutput.preprocessedTokens.push(rawTokens[i]);
        }
    }

    return context.intermediateOutput;
}

function handleDirectiveTokens(context: DirectivePreprocessorContext, directiveTokens: TokenObject[]) {
    const directiveHighlight = HighlightForToken.Macro;
    directiveTokens[0].setHighlight(directiveHighlight); // '#'
    if (directiveTokens.length === 1) {
        return;
    }

    if (directiveTokens[1].text === 'include') {
        // e.g., #include "filename"
        directiveTokens[1].setHighlight(directiveHighlight);

        if (!context.isActiveBlock) {
            return;
        }

        // Validate the include directive.
        const fileName = directiveTokens[2];
        if (fileName === undefined) {
            diagnostic.error(directiveTokens[1].location, 'Expected a file name in the include directive.');
            return;
        }

        if (!fileName.isStringToken()) {
            diagnostic.error(directiveTokens[2].location, 'Expected a string literal in the include directive.');
            return;
        }

        context.intermediateOutput.includePathTokens.push(fileName);
    } else if (directiveTokens[1].text === 'define') {
        // e.g., #define SYMBOL_NAME
        directiveTokens[1].setHighlight(directiveHighlight);

        if (!context.isActiveBlock) {
            return;
        }

        const symbolName = directiveTokens[2];
        if (symbolName === undefined) {
            diagnostic.error(directiveTokens[1].location, 'Expected a symbol name in the define directive.');
            return;
        }

        if (!symbolName.isIdentifierToken()) {
            diagnostic.error(directiveTokens[2].location, 'Expected a identifier token.');
            return;
        }

        context.intermediateOutput.definedSymbols.add(directiveTokens[2].text);
    } else if (directiveTokens[1].text === 'if') {
        // e.g., #if SYMBOL_NAME, #if 1
        directiveTokens[1].setHighlight(directiveHighlight);

        const condition = getIfDirectiveCondition(context, directiveTokens);
        if (condition === undefined) {
            return;
        }

        context.ifDirectiveBlockStack.push({
            tag: '#if',
            start: getDirectiveBlockStart(directiveTokens),
            isActiveBlock: condition,
            hasActiveBranch: condition,
            hasElse: false
        });

        updateInactiveBlockStatus(context);
    } else if (directiveTokens[1].text === 'elif') {
        // e.g., #elif SYMBOL_NAME, #elif 1
        directiveTokens[1].setHighlight(directiveHighlight);

        const currentIfDirectiveBlock = getCurrentIfDirectiveBlock(context);
        if (!currentIfDirectiveBlock) {
            diagnostic.error(directiveTokens[1].location, 'Missing `#if`');
            return;
        }

        if (currentIfDirectiveBlock.hasElse) {
            diagnostic.error(directiveTokens[1].location, '`#elif` cannot appear after `#else`.');
            return;
        }

        reportInactiveDirectiveBlockIfNeeded(
            context,
            currentIfDirectiveBlock,
            (directiveTokens[0].prevRaw ?? directiveTokens[0]).location.end
        );

        const condition = getIfDirectiveCondition(context, directiveTokens);
        currentIfDirectiveBlock.start = getDirectiveBlockStart(directiveTokens);
        if (condition === undefined) {
            currentIfDirectiveBlock.isActiveBlock = false;
            updateInactiveBlockStatus(context);
            return;
        }

        currentIfDirectiveBlock.isActiveBlock = !currentIfDirectiveBlock.hasActiveBranch && condition;
        currentIfDirectiveBlock.hasActiveBranch =
            currentIfDirectiveBlock.hasActiveBranch || currentIfDirectiveBlock.isActiveBlock;

        updateInactiveBlockStatus(context);
    } else if (directiveTokens[1].text === 'else') {
        // e.g., #else
        directiveTokens[1].setHighlight(directiveHighlight);

        const currentIfDirectiveBlock = getCurrentIfDirectiveBlock(context);
        if (!currentIfDirectiveBlock) {
            diagnostic.error(directiveTokens[1].location, 'Missing `#if`');
            return;
        }

        if (currentIfDirectiveBlock.hasElse) {
            diagnostic.error(directiveTokens[1].location, 'Duplicate `#else`.');
            return;
        }

        reportInactiveDirectiveBlockIfNeeded(
            context,
            currentIfDirectiveBlock,
            (directiveTokens[0].prevRaw ?? directiveTokens[0]).location.end
        );

        currentIfDirectiveBlock.start = getDirectiveBlockStart(directiveTokens);
        currentIfDirectiveBlock.isActiveBlock = !currentIfDirectiveBlock.hasActiveBranch;
        currentIfDirectiveBlock.hasActiveBranch =
            currentIfDirectiveBlock.hasActiveBranch || currentIfDirectiveBlock.isActiveBlock;
        currentIfDirectiveBlock.hasElse = true;

        updateInactiveBlockStatus(context);
    } else if (directiveTokens[1].text === 'endif') {
        // e.g., #endif
        directiveTokens[1].setHighlight(directiveHighlight);

        const currentIfDirectiveBlock = getCurrentIfDirectiveBlock(context);
        if (!currentIfDirectiveBlock) {
            diagnostic.error(directiveTokens[1].location, 'Missing `#if`');
            return;
        }

        reportInactiveDirectiveBlockIfNeeded(
            context,
            currentIfDirectiveBlock,
            (directiveTokens[0].prevRaw ?? directiveTokens[0]).location.end
        );

        context.ifDirectiveBlockStack.pop();

        updateInactiveBlockStatus(context);
    } else {
        if (directiveTokens[1] != null) {
            directiveTokens[1].setHighlight(HighlightForToken.Label);
        }
    }
}

function sliceTokenListBySameLine(tokens: TokenObject[], head: number): TokenObject[] {
    let tail = head;
    for (let i = head; i < tokens.length - 1; i++) {
        if (tokens[i].location.end.isSameLine(tokens[i + 1].location.start) === false) {
            break;
        }

        tail = i + 1;
    }

    return tokens.slice(head, tail + 1);
}

function createCombinedStringToken(lhs: StringToken, rhs: StringToken): TokenObject {
    const tokenText = '"' + lhs.getStringContent() + rhs.getStringContent() + '"'; // FIXME?
    return StringToken.createVirtual(tokenText, new TokenRange(lhs, rhs));
}
